added MainScreen
Veselchak-U/boost_grade_start pull request #1
Opened 2022-01-04 21:51 UTC by Veselchak-U

2022-01-05 08:29 UTC, Veselchak-U commented
Скриншот экрана:
![index](https://user-images.githubusercontent.com/57040655/148185350-6a5bcf99-0674-4e2e-94fb-9fc53972a1e9.jpg)

2022-01-05 11:47 UTC, dkrutskikh requested changes

2022-01-05 11:47 UTC, dkrutskikh commented on lib/app/navigator/route_helper.dart
> +      builder: (context) => const MainScreen(), //const HomeScreen(),
@Veselchak-U как я понимаю MainScreen будет домашней (корневой), не вижу смысла оставлять комментарий (но это чисто вкусовщина)

2022-01-05 11:47 UTC, dkrutskikh commented on lib/features/main/view/components/navigation_button.dart
> +    final colorTheme = AppColorTheme.of(context);
@Veselchak-U мы можем как-то отказаться от постоянного хождения по инхеритед виджетам?

2022-01-05 11:47 UTC, dkrutskikh commented on lib/features/main/view/components/navigation_button.dart
> +    return Container(
@Veselchak-U я так понимаю тут сверстана кнопка. Подскажи чем не устроила уже готовая кнопка из набора material виджетов?

2022-01-06 20:26 UTC, Veselchak-U commented on lib/app/navigator/route_helper.dart
> +      builder: (context) => const MainScreen(), //const HomeScreen(),
Удалил.

2022-01-06 20:27 UTC, Veselchak-U commented on lib/features/main/view/components/navigation_button.dart
> +    final colorTheme = AppColorTheme.of(context);
Добавил их в context через extension.

2022-01-06 20:29 UTC, Veselchak-U commented on lib/features/main/view/components/navigation_button.dart
> +    return Container(
Не знал, что у стандартной TextButton есть ripple-эффект. Раньше вроде не было. Переделал.

2022-01-07 03:55 UTC, dkrutskikh commented on lib/features/main/view/components/navigation_button.dart
> +    final colorTheme = AppColorTheme.of(context);
так это тоже самое получилось, вы просто спрятали код в extension. Во material app у Flutter есть понятие темы - мы можем использовать ее?

2022-01-07 03:56 UTC, dkrutskikh commented on lib/features/main/view/components/navigation_button.dart
> +    return Container(
можно еще посмотреть в сторону https://api.flutter.dev/flutter/material/ElevatedButton-class.html

2022-01-07 03:59 UTC, dkrutskikh approved these changes

2022-01-08 23:59 UTC, merged