added SquaresScreen
Veselchak-U/boost_grade_start pull request #2
Opened 2022-01-09 02:31 UTC by Veselchak-U

2022-01-09 05:52 UTC, dkrutskikh requested changes

2022-01-09 05:52 UTC, dkrutskikh commented on lib/features/squares/view/squares_screen.dart
> +        _random.nextInt(256),
@Veselchak-U это точно хорошая идея генерировать полу прозрачные квадраты?

2022-01-09 05:52 UTC, dkrutskikh commented on lib/features/squares/view/squares_screen.dart
> +  late List<ColorBox> _squares;
@Veselchak-U класть виджеты в стейт это антипаттерн, виджеты надо создавать только в методе билд

2022-01-09 05:52 UTC, dkrutskikh commented on lib/features/squares/view/squares_screen.dart
> +          key: ValueKey(index),
@Veselchak-U зачем виджетам ключ?

2022-01-09 05:53 UTC, dkrutskikh requested changes

2022-01-09 05:53 UTC, dkrutskikh commented on lib/app/asset/asset.dart
> +  final iconEdit = _path + 'icon_edit.svg';
@Veselchak-U в целом ок, но на будущее - вначале стоит посмотреть уже готовую иконку в наборах material или купертино

2022-01-09 09:41 UTC, Veselchak-U commented on lib/features/squares/view/squares_screen.dart
> +        _random.nextInt(256),
Исправил.

2022-01-09 09:42 UTC, Veselchak-U commented on lib/features/squares/view/squares_screen.dart
> +  late List<ColorBox> _squares;
Исправил.

2022-01-09 09:43 UTC, Veselchak-U commented on lib/features/squares/view/squares_screen.dart
> +          key: ValueKey(index),
Где-то я читал, что это хорошо для производительности в больших скроллируемых списках. В данном случае согласен - это лишнее.

2022-01-09 09:43 UTC, Veselchak-U commented on lib/app/asset/asset.dart
> +  final iconEdit = _path + 'icon_edit.svg';
В готовых наборах иконка отличается от макета, поэтому вынес в SVG.

2022-01-09 19:56 UTC, dkrutskikh requested changes

2022-01-09 19:56 UTC, dkrutskikh commented on lib/features/squares/view/squares_screen.dart
> +            child: FloatingActionButton(
@Veselchak-U для FloatingActionButton у Scaffold есть свое поле, поищите его

2022-01-09 20:04 UTC, Veselchak-U commented on lib/features/squares/view/squares_screen.dart
> +            child: FloatingActionButton(
Знаю, но у него не настраивается padding. А в макете padding нестандартный. Поэтому через Stack.

2022-01-12 03:49 UTC, dkrutskikh commented on lib/features/squares/view/squares_screen.dart
> +            child: FloatingActionButton(
@Veselchak-U мы с вами в личке обсуждали о возможности переопределить `Offset getOffset(ScaffoldPrelayoutGeometry scaffoldGeometry);`

2022-01-12 21:52 UTC, Veselchak-U commented on lib/features/squares/view/squares_screen.dart
> +            child: FloatingActionButton(
Переопределил.

2022-01-13 03:02 UTC, dkrutskikh approved these changes

2022-01-13 20:17 UTC, merged