Task 3 colour list screen
Veselchak-U/boost_grade_start pull request #3
Opened 2022-01-09 19:51 UTC by Veselchak-U

![index2](https://user-images.githubusercontent.com/57040655/148698268-5de02c35-6f3c-4c08-8b7d-f0e0b85aafd6.jpg)
![index](https://user-images.githubusercontent.com/57040655/148698276-557d0336-289a-4265-b567-320f50837b7a.jpg)

2022-01-11 13:27 UTC, dkrutskikh requested changes

2022-01-11 13:27 UTC, dkrutskikh commented on lib/features/colour_list/view/colour_list_screen.dart
> +  void _changeColors() {
@Veselchak-U Дмитрий в целом это ок - но эта функция нарушает принцип единой отвественности, она и генерирует новые цвета и обновляет состояние виджета

2022-01-11 13:27 UTC, dkrutskikh commented on lib/features/colour_list/view/colour_list_screen.dart
> +          onPressed: () => Navigator.pop(context),
@Veselchak-U вот с этим надо-бы разобраться, обычно навигатор сам рисует иконку выхода назад

2022-01-11 13:27 UTC, dkrutskikh commented on lib/features/colour_list/view/colour_list_screen.dart
> +            itemBuilder: (BuildContext context, int index) => Padding(
@Veselchak-U посмотрите в сторону ListView.separated вместо обязательного оборачивания в паддинг

2022-01-11 19:44 UTC, Veselchak-U commented on lib/features/colour_list/view/colour_list_screen.dart
> +  void _changeColors() {
Исправил.

2022-01-11 19:45 UTC, Veselchak-U commented on lib/features/colour_list/view/colour_list_screen.dart
> +          onPressed: () => Navigator.pop(context),
Та же история - в макете стрелка нестандартная, поэтому так.

2022-01-11 19:45 UTC, Veselchak-U commented on lib/features/colour_list/view/colour_list_screen.dart
> +            itemBuilder: (BuildContext context, int index) => Padding(
Переделал.

2022-01-12 17:47 UTC, dkrutskikh approved these changes

2022-01-12 17:47 UTC, dkrutskikh commented on lib/features/colour_list/view/colour_list_screen.dart
> +          onPressed: () => Navigator.pop(context),
макеты  под андройд, у вас на iOS симуляторе рисуется другая иконка

2022-01-13 20:50 UTC, Veselchak-U commented on lib/features/colour_list/view/colour_list_screen.dart
> +          onPressed: () => Navigator.pop(context),
Вернул стрелку по-умолчанию.

2022-01-13 21:06 UTC, merged