Task 4 codelabs
Veselchak-U/boost_grade_start pull request #4
Opened 2022-01-11 21:59 UTC by Veselchak-U

![index1](https://user-images.githubusercontent.com/57040655/149027975-a7d1a36c-c947-45c5-93bc-3df9c8a7e88e.jpg)
![index2](https://user-images.githubusercontent.com/57040655/149027981-fa504f4c-6e69-47d5-aaf5-bac023530087.jpg)
![index3](https://user-images.githubusercontent.com/57040655/149028005-c0463a2b-577b-47f3-aec7-72356c6d9474.jpg)

2022-01-14 03:14 UTC, dkrutskikh requested changes

2022-01-14 03:14 UTC, dkrutskikh commented on lib/features/codelabs/view/codelabs_screen.dart
> +    _items.addAll(generateWordPairs().take(10));
@Veselchak-U вот тут типичная ошибка, во время построения макета экрана мы мутируем состояние виджета. Как мы можем это переделать?

2022-01-14 22:14 UTC, Veselchak-U commented on lib/features/codelabs/view/codelabs_screen.dart
> +    _items.addAll(generateWordPairs().take(10));
Переделал.

2022-01-15 19:57 UTC, dkrutskikh requested changes

2022-01-15 19:57 UTC, dkrutskikh commented on lib/features/codelabs/view/codelabs_screen.dart
> +  Widget _buildItemList() {
@Veselchak-U использовать helper функции, это анти-паттерн https://www.youtube.com/watch?v=IOyq-eTRhvo&t=7s&ab_channel=Flutter

2022-01-16 00:33 UTC, Veselchak-U commented on lib/features/codelabs/view/codelabs_screen.dart
> +  Widget _buildItemList() {
Переделал.

2022-01-16 05:40 UTC, dkrutskikh commented on lib/features/codelabs/view/codelabs_screen.dart
> +      _getNextPage();
@Veselchak-U супер! Круто что сами нашли этот кейс.

2022-01-16 05:40 UTC, dkrutskikh approved these changes

2022-01-16 09:07 UTC, merged